//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task5mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    
        public virtual TaskEmployee TaskEmployee { get; set; }
    }
}
